name: ${project.artifactId}
version: ${project.version}
authors: [valadian, rourke750, ProgrammerDan, Maxopoly, DeadBeef, Protonull, Okx, mindless728, Tealnerd]
main: ${plugin.main}
api-version: ${minecraft.version}
commands:
  config: {}
permissions:
  cmc.config.save:
    default: op
