name: Build
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  call_build:
    uses: CivMC/.github/.github/workflows/gradle_build.yml@master
  call_sonar:
    uses: CivMC/.github/.github/workflows/gradle_sonarqube.yml@master
