name: ${pluginName}
version: ${version}
authors:
  - valadian
  - rourke750
  - ProgrammerDan
  - Maxopoly
  - DeadBeef
  - Protonull
  - Okx
  - mindless728
  - Tealnerd
  - Diet-Cola
  - Aleksey-Terzi
description: ${description}
main: vg.civcraft.mc.civmodcore.CivModCorePlugin
api-version: ${api_version}
permissions:
  cmc.config.save:
    default: op
  cmc.configany:
    default: op
  cmc.debug:
    default: op
